[package]
name = "YARS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7"
block-modes = "0.8"
block-padding = "0.3"
hex = "0.4"


[[bin]]
name = "YARS"
path = "src/main.rs"
